version: '3'
services: 
  web:
    container_name: test-docker-nodejsServer
    build: .
    ports:
     - "3000:3000"
    image: "leesw/docker-nodejsserver"
  db:
    image: "leesw/nodejs-mysql"
    container_name: test-mysql
    ports:
      - "3306:3306"

    
